Accounts/urls.py
from django.urls import path
from . import views



app_name = "accounts"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
]

Main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = "main"

urlpatterns = [
    path('', views.home, name="home"),
    path('cart/', views.cart, name="cart"),
	path('checkout/', views.checkout, name="checkout"),
    path('details/<int:id>/', views.detail, name="detail"),
    path('addmovies/', views.add_movies, name="add_movies"),
    path('editmovies/<int:id>/', views.edit_movies, name="edit_movies"),
    path('deletemovies/<int:id>/', views.delete_movies, name="delete_movie"),
    path('addreview/<int:id>/', views.add_review, name="add_review"),
    path('editreview/<int:movie_id>/<int:review_id>/', views.edit_review, name="edit_review"),
    path('deletereview/<int:movie_id>/<int:review_id>/', views.delete_review, name="delete_review"),
    path('update_item/', views.updateItem, name="update_item"),
    path('process_order/', views.processOrder, name="process_order"),
    path('addcategories/', views.add_category, name="add_category"),
    path('deletecategories/<int:id>/', views.delete_category, name="delete_category"),


    
    
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Movies_Site/urls.py
from django.contrib import admin
from django.urls import path,include
import Accounts


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Main.urls')),
    path('accounts/',include('Accounts.urls')),
        path('profile/', Accounts.views.profile, name="profile")  

    
]

Main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.functions import Length
from PIL import Image


# Create your models here.

class Category(models.Model):
	title=models.CharField(max_length=200)
	def __str__(self):
		return self.title
	def __unicode__(self):
		return self.title


# Create your models here.
class Movie(models.Model):
    # fields for the movie table
 
    name = models.CharField(max_length=300)
    director = models.CharField(max_length=300)
    category = models.ForeignKey(Category, on_delete=models.CASCADE,null=True)
    price = models.FloatField(null=True)
    cast = models.CharField(max_length=800)
    description = models.TextField(max_length=5000)
    release_date = models.DateField()
    averageRating = models.FloatField(default=0)
    image = models.URLField(default=None, null=True)
    digital = models.BooleanField(default=False,null=True, blank=True)


    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

class Review(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(max_length=5000,null=True,blank=True)
    rating = models.FloatField(default=0)

    def __str__(self):
        return self.user.username


class Order(models.Model):
	customer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
	date_ordered = models.DateTimeField(auto_now_add=True)
	complete = models.BooleanField(default=False)
	transaction_id = models.CharField(max_length=100, null=True)

	def __str__(self):
		return str(self.id)
		
	@property
	def shipping(self):
		shipping = False
		orderitems = self.orderitem_set.all()
		for i in orderitems:
			if i.movie.digital == False:
				shipping = True
		return shipping

	@property
	def get_cart_total(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.get_total for item in orderitems])
		return total 

	@property
	def get_cart_items(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.quantity for item in orderitems])
		return total

class OrderItem(models.Model):
	movie = models.ForeignKey(Movie, on_delete=models.SET_NULL, null=True)
	order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
	quantity = models.IntegerField(default=0, null=True, blank=True)
	date_added = models.DateTimeField(auto_now_add=True)

	@property
	def get_total(self):
		total = self.movie.price * self.quantity
		return total

class ShippingAddress(models.Model):
	customer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
	order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
	address = models.CharField(max_length=200, null=False)
	city = models.CharField(max_length=200, null=False)
	state = models.CharField(max_length=200, null=False)
	zipcode = models.CharField(max_length=200, null=False)
	date_added = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.address

Main/forms.py
from django import forms
from .models import *
import django_filters
from django.contrib.auth.forms import UserCreationForm
from Accounts.models import Profile
# movie add form
class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('name', 'director', 'cast', 'description', 'release_date', 'image','category','price')
class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('title',)


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ("comment", "rating")


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

Main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from Accounts.models import Profile
from .forms import *
from django.db.models import Avg
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib import messages
from django.db.models.functions import Length
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse
import json
import datetime

from .filters import MovieFilter

# Create your views here.
def home (request) :   
    allmovies_list = Movie.objects.all() # select * from movie
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else :
        item = []
        order = {'get_cart_total':0,'get_cart_items':0,'shipping':False}
        cartItems = order['get_cart_items']
    myFilter = MovieFilter(request.GET, queryset=allmovies_list)
    allmovies_list = myFilter.qs  
    paginator = Paginator(allmovies_list, 3)
    page = request.GET.get('page')
    try:
        allmovies = paginator.page(page)
    except PageNotAnInteger:
        allmovies = paginator.page(1)
    except EmptyPage:
        allmovies = paginator.page(paginator.num_page)
    

    context = {
        "movies" : allmovies ,
        'myFilter' : myFilter,
        'cartItems':cartItems
    }
    return render(request, 'main/index.html',context)

# detail page
def detail(request, id):
    movie = Movie.objects.get(id=id) # select * from movie where id=id
    reviews = Review.objects.filter(movie=id).order_by("-comment")

    average = reviews.aggregate(Avg("rating"))["rating__avg"]
    if average == None:
        average = 0
    average = round(average, 2)
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else :
        item = []
        order = {'get_cart_total':0,'get_cart_items':0,'shipping':False}
        cartItems = order['get_cart_items']
    


    context = {
        "movie": movie,
        "reviews": reviews,
        "average": average,
        'cartItems':cartItems,
        
    
    }
    return render(request, 'main/details.html', context)

# add movies to the database
def add_movies(request):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            if request.method == "POST":
                form = MovieForm(request.POST or None)

                # check if the form is valid
                if form.is_valid():
                    data = form.save(commit=False)
                    data.save()
                    messages.success(request,f'Added a new Movie Successfully!')
                    return redirect("main:home")
            else:
                form = MovieForm()

            return render(request, 'main/addmovies.html',{"form": form, "controller": "Add Movies"})
        
        # if they are not admin
        else:
            return redirect("main:home")

    # if they are not loggedin
    return redirect("accounts:login")   


def add_category(request):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            if request.method == "POST":
                form = CategoryForm(request.POST or None)

                # check if the form is valid
                if form.is_valid():
                    data = form.save(commit=False)
                    data.save()
                    messages.success(request,f'Added a new Category Successfully!')
                    return redirect("main:home")
            else:
                form = CategoryForm()

            categories=Category.objects.all()
            return render(request, 'main/addcategory.html',{"form": form,"categories":categories, "controller": "Add Category"})
        
        # if they are not admin
        else:
            return redirect("main:home")

    # if they are not loggedin
    return redirect("accounts:login")     


# edit the movie
def edit_movies(request, id):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            # get the movies linked with id
            movie = Movie.objects.get(id=id)

            # form check
            if request.method == "POST":
                form = MovieForm(request.POST or None, instance=movie)
                # check if form is valid
                if form.is_valid():
                    data = form.save(commit=False)
                    data.save()

                    messages.info(request,f'The Movie has been Updated!')
                    return redirect("main:detail", id)
            else:
                form = MovieForm(instance=movie)

            return render(request, 'main/addmovies.html', {"form": form, "controller": "Edit Movies"})
        # if they are not admin
        else:
            return redirect("main:home")

    # if they are not loggedin
    return redirect("accounts:login") 


# delete movies
def delete_movies(request, id):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            # get the moveis
            movie = Movie.objects.get(id=id)

            # delte the movie
            movie.delete()
            messages.info(request,f'The Movie has been Deleted!')
            return redirect("main:home")
        # if they are not admin
        else:
            return redirect("main:home")

    # if they are not loggedin
    return redirect("accounts:login")

def delete_category(request, id):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            # get the moveis
            cat = Category.objects.get(id=id)

            # delte the movie
            cat.delete()
            messages.info(request,f'The Category has been Deleted!')
            return redirect("main:home")
        # if they are not admin
        else:
            return redirect("main:home")

    # if they are not loggedin
    return redirect("accounts:login")


def add_review(request, id):
    if request.user.is_authenticated:
        movie = Movie.objects.get(id=id)
        if request.method == "POST":
            form = ReviewForm(request.POST or None)
            if form.is_valid():
                data = form.save(commit=False)
                if request.POST["comment"]:
                    data.comment = request.POST["comment"]
                data.rating = request.POST["rating"]
                data.user = request.user
                data.movie = movie
                data.save()
                messages.success(request,f'Added a Review Successfully!')
                return redirect("main:detail", id)
        else:
            form = ReviewForm()
        return render(request, 'main/details.html', {"form": form})
    else:
        return redirect("accounts:login")

# edit the review
def edit_review(request, movie_id, review_id):
    if request.user.is_authenticated:
        movie = Movie.objects.get(id=movie_id)
        # review
        review = Review.objects.get(movie=movie, id=review_id)

        # check if the review was done by the logged in user
        if request.user == review.user:
            # grant permission
            if request.method == "POST":
                form = ReviewForm(request.POST, instance=review)
                if form.is_valid():
                    data = form.save(commit=False)
                    if (data.rating > 5) or (data.rating < 0):
                         error = "Out or range. Please select rating from 0 to 5."
                         return render(request, 'main/editreview.html', {"error": error, "form": form})
                    else:
                        data.save()
                        messages.info(request,f'The Review has been Updated!')
                        return redirect("main:detail", movie_id)
            else:
                form = ReviewForm(instance=review)
            return render(request, 'main/editreview.html', {"form": form})
        else:
            return redirect("main:detail", movie_id)
    else:
        return redirect("accounts:login")

# delete reivew
def delete_review(request, movie_id, review_id):
    if request.user.is_authenticated:
        movie = Movie.objects.get(id=movie_id)
        # review
        review = Review.objects.get(movie=movie, id=review_id)

        # check if the review was done by the logged in user
        if request.user == review.user:
            # grant permission to delete
            review.delete()
            messages.info(request,f'The Review has been Deleted!')

        return redirect("main:detail", movie_id)
            
    else:
        return redirect("accounts:login")


def cart(request):
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items

        context = {
        "items": items ,
        "order": order,
        'cartItems':cartItems
      }   
    return render(request, 'main/cart.html', context)
def checkout(request):
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
        context = {
        "items": items ,
        "order": order ,
        'cartItems':cartItems
        }
    return render(request, 'main/checkout.html', context)

def updateItem(request):
	data = json.loads(request.body)
	movieId = data['movieId']
	action = data['action']
	print('Action:', action)

Main/templates/Main/Checkout.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
<div class="row">
	<div class="col-lg-6">
		<div class="box-element" id="form-wrapper">
			<form id="form">
				<div id="user-info">
					<div class="form-field">
						<input required class="form-control" type="text" name="name" placeholder="Name..">
					</div>
					<div class="form-field">
						<input required class="form-control" type="email" name="email" placeholder="Email..">
					</div>
				</div>

				<div id="shipping-info">
					<hr>
					<h3>Shipping Information</h3>
					<hr>
					<div class="form-field">
						<input class="form-control" type="text" name="address" placeholder="Address..">
					</div>
					<div class="form-field">
						<input class="form-control" type="text" name="city" placeholder="City..">
					</div>
					<div class="form-field">
						<input class="form-control" type="text" name="state" placeholder="State..">
					</div>
					<div class="form-field">
						<input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
					</div>
					<div class="form-field">
						<input class="form-control" type="text" name="country" placeholder="Zip code..">
					</div>
				</div>

				<hr>
				<input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
			</form>
		</div>

		<br>
		<div class="box-element hidden" id="payment-info">
			<small>Paypal Options</small>
		</div>

	</div>

	<div class="col-lg-6">
		<div class="box-element">
			<a class="btn btn-outline-dark" href="{% url 'main:cart' %}">&#x2190; Back to Cart</a>
			<hr>
			<h3>Order Summary</h3>
			<hr>
			{% for item in items %}

			<div class="row">
				<div class="col-sm-6 col-md-6 col-lg-6">
					<img class="row-image" src="{{item.movie.image}}">
				</div>
				<div class="col-sm-6 col-md-6 col-lg-6">
					<div>
						<p>{{item.movie.name}}</p>
					</div>
					<div>
						<p>${{item.movie.price|floatformat:2}} x{{item.quantity}}</p>
					</div>
				</div>
			</div>
			{% endfor %}
			<hr>
			<div class="row ml-2 mt-2">
				<h5 class="mr-2"><strong>Items: </strong>x{{order.get_cart_items}}</h5>
				<h5><strong>Total: </strong>${{order.get_cart_total|floatformat:2}}</h5>
			</div>
		</div>
	</div>
</div>

<script src="https://www.paypal.com/sdk/js?client-id=YOUR-CLIENT-ID&currency=USD&disable-funding=credit"></script>

<script>
	var total = '{{order.get_cart_total}}'
	// Render the PayPal button into #paypal-button-container
	paypal.Buttons({

		style: {
			color: 'blue',
			shape: 'rect',
		},

		// Set up the transaction
		createOrder: function (data, actions) {
			return actions.order.create({
				purchase_units: [{
					amount: {
						value: parseFloat(total).toFixed(2)
					}
				}]
			});
		},

		// Finalize the transaction
		onApprove: function (data, actions) {
			return actions.order.capture().then(function (details) {
				// Show a success message to the buyer
				submitFormData()
			});
		}

	}).render('#paypal-button-container');
</script>


<script type="text/javascript">
	var shipping = '{{order.shipping}}'

	if (shipping == 'False') {
		document.getElementById('shipping-info').innerHTML = ''
	}

	if (user != 'AnonymousUser') {
		document.getElementById('user-info').innerHTML = ''
	}

	if (shipping == 'False' && user != 'AnonymousUser') {
		//Hide entire form if user is logged in and shipping is false
		document.getElementById('form-wrapper').classList.add("hidden");
		//Show payment if logged in user wants to buy an item that does not require shipping
		document.getElementById('payment-info').classList.remove("hidden");
	}

	var form = document.getElementById('form')
	form.addEventListener('submit', function (e) {
		e.preventDefault()
		console.log('Form Submitted...')
		document.getElementById('form-button').classList.add("hidden");
		document.getElementById('payment-info').classList.remove("hidden");
	})

	/*
	document.getElementById('make-payment').addEventListener('click', function(e){
		submitFormData()
	})
	*/

	function submitFormData() {
		console.log('Payment button clicked')

		var userFormData = {
			'name': null,
			'email': null,
			'total': total,
		}

		var shippingInfo = {
			'address': null,
			'city': null,
			'state': null,
			'zipcode': null,
		}

		if (shipping != 'False') {
			shippingInfo.address = form.address.value
			shippingInfo.city = form.city.value
			shippingInfo.state = form.state.value
			shippingInfo.zipcode = form.zipcode.value
		}

		if (user == 'AnonymousUser') {
			userFormData.name = form.name.value
			userFormData.email = form.email.value
		}

		console.log('Shipping Info:', shippingInfo)
		console.log('User Info:', userFormData)

		var url = "/process_order/"
		fetch(url, {
			method: 'POST',
			headers: {
				'Content-Type': 'applicaiton/json',
				'X-CSRFToken': csrftoken,
			},
			body: JSON.stringify({ 'form': userFormData, 'shipping': shippingInfo }),

		})
			.then((response) => response.json())
			.then((data) => {
				console.log('Success:', data);
				alert('Transaction completed');

				cart = {}
				document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"

				window.location.href = "{% url 'main:home' %}"

			})
	}
</script>
{% endblock content %}

Main/templates/Main/base.html
<!doctype html>
<html lang="en">

<head>

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
  <script src='https://kit.fontawesome.com/a076d05399.js'></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
  {% block head %}

  {% endblock %}
 

  <script type="text/javascript">
    var user = '{{request.user}}'
    function getToken(name) {
      var cookieValue = null;
      if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
          var cookie = cookies[i].trim();
          // Does this cookie string begin with the name we want?
          if (cookie.substring(0, name.length + 1) === (name + '=')) {
            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
            break;
          }
        }
      }
      return cookieValue;
    }
    var csrftoken = getToken('csrftoken')
  </script>
  <title>Moviereview</title>

</head>
<style>
  .checked {
    color: red;
  }

  .my-btn {
    background-color: inherit !important;
    border: 0 !important;
  }
</style>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-info text-white">
    <a class="navbar-brand" href="{% url 'main:home' %}">Movie Review</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'main:home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:add_movies' %}">Add Movies</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:add_category' %}">Add Category</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            {{ user.username }}
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'profile' %}">My Profile</a>

            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
          </div>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
        </li>
        {% endif %}


      </ul>

      {% if request.user.is_authenticated %}
      <div class="form-inline my-2 my-lg-0">


        <a href="{% url 'main:cart' %}">
          <img id="cart-icon" src="{% static 'images/shopping-cart-512.png' %}">
        </a>
        <p id="cart-total">{{cartItems}}</p>
        {% endif %}

      </div>
  </nav>

  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12">
      {% if messages %}
      {% for m in messages %}
      <div class="alert alert-{{ m.tags }}" style="text-align: center;">
        {{ m }}
      </div>
      {% endfor %}
      {% endif %}
    </div>
  </div>
  {% block content %}{% endblock %}







  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
    crossorigin="anonymous"></script>
  <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>

  <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
</body>

</html>

Main/templates/Main/details.html
{% extends 'main/base.html' %}

{% load static %}

{% block head %}
<script src="{% static 'js/rating.js' %}" type="text/javascript"></script>
{% endblock %}

{% block content %}


<div class="container">
    <br>
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-4">
                    <img src="{{ movie.image }}" alt="{{ movie.name }}" class="img-fluid">
                </div>
                <div class="col-md-8">
                    <h3 class="text-center">
                        {{ movie.name }}
                    </h3>
                    <p>{{ movie.description }}</p>
                    <h5>Director: {{ movie.director }}</h5>
                    <h5>Cast: {{ movie.cast }}</h5>
                    <h5>category:{{ movie.category}}</h5>
                    <h5>price: ${{ movie.price}}</h5>
                    <table>
                        <tbody>
                            <tr class='rating'>
                                <td>
                                   
                                    <span class="number-rating"></span>
                                    <h5>Rating: <span class='ratingValue'>{{ average }}</span>
                                        <span class="stars-outer">
                                            <div class="stars-inner"></div>
                                        </span>
                                    </h5>
                                    

                                </td>
                            </tr>

                        </tbody>
                    </table>



                    {% if request.user.is_authenticated %}
                    {% if request.user.is_superuser %}
                    <a href="{% url 'main:edit_movies' movie.id %}" class="btn btn-warning">Edit Movie</a>
                    <a href="{% url 'main:delete_movie' movie.id %}" class="btn btn-danger"
                        onclick="return confirm('Are you sure you want to delete this?');">Delete Movie</a>
                    {% endif %}
                    <button data-movie="{{movie.id}}" data-action="add"
                        class="btn btn-outline-secondary add-btn update-cart">Add to Cart</button>
                    {% endif %}

                </div>
            </div>
        </div>

        <br>
        <div class="card">
            <div class="card-body">
                <h3 class="text-center">Add Review</h3>
                <form action="{% url 'main:add_review' movie.id %}" method="POST">
                    {% csrf_token %}

                    <label for="comment">Review</label>
                    <textarea name="comment" id="comment" cols="30" rows="5" class="form-control"></textarea>

                    <label for="rating">Rating</label>
                    <input type="range" id="rangeInput" name="rating" min="0" max="5" value="0" step="0.5"
                        oninput="amount.value=rangeInput.value">


                    <output name="amount" id="amount" for="rangeInput">0</output>

                    <br>

                    <input type="submit" class="btn btn-danger" value="Add Review">

                </form>
            </div>
        </div>
    </div>

    <br>
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Reviews</h3>
            {% for review in reviews %}
            <div class="card" style="background-color: #f5eeee;">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-3">
                            <h5 class="text-left">{{ review.user.username }}</h5>
                            <h5>{{ review.rating }}</h5>
                            {% if request.user == review.user %}
                            <a href="{% url 'main:edit_review' movie.id review.id %}">Edit</a>
                            <a href="{% url 'main:delete_review' movie.id review.id %}"
                                onclick="return confirm('Are you sure you want to delete this?');">Delete</a>
                            {% endif %}

                        </div>
                        <div class="col-md-9">
                            <p>{% if review.comment %}
                                {{ review.comment }}
                                {% else %}
                                No Comment.
                                {% endif %}</p>
                        </div>
                    </div>
                </div>
            </div>
            <br>
            {% endfor %}
        </div>
    </div>



    {% endblock %}